name = "terminal_link"
version = "1.0.0"
description = "Easily create clickable terminal hyperlinks"
licences = ["MIT"]
repository = { type = "github", user = "hougesen", repo = "terminal_link" }

[dependencies]
envoy = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.57.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
